/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.lexer;

import java.io.*;
import cida.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbreBloco(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechaBloco(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParEsq(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParDir(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoisPontos(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoVirgula(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAspas(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColcheteEsq(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColcheteDir(line, pos); }
    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumeros(text, line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSoma(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenos(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribuicao(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenor(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorIgual(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComparacao(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNegacao(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoisMaior(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIn(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCase(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThat(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConsidering(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFrom(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTo(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBy(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAs(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLong(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnd(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOr(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNot(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TXor(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDo(line, pos); }
    Token new37(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCode(text, line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TShow(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCapture(line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioLinha(text, line, pos); }
    Token new41(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioBloco(text, line, pos); }
    Token new42(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new43(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TModificadores(text, line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSymbol(line, pos); }
    Token new45(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(text, line, pos); }
    Token new46(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnswer(text, line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVector(line, pos); }
    Token new48(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVetorSymbol(text, line, pos); }
    Token new49(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVetores(text, line, pos); }
    Token new50(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVazio(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {12, 12, 3}, {13, 13, 4}, {32, 32, 5}, {33, 33, 6}, {34, 34, 7}, {37, 37, 8}, {40, 40, 9}, {41, 41, 10}, {42, 42, 11}, {43, 43, 12}, {44, 44, 13}, {45, 45, 14}, {46, 46, 15}, {47, 47, 16}, {48, 57, 17}, {58, 58, 18}, {59, 59, 19}, {60, 60, 20}, {61, 61, 21}, {62, 62, 22}, {65, 90, 23}, {91, 91, 24}, {92, 92, 25}, {93, 93, 26}, {97, 97, 27}, {98, 98, 28}, {99, 99, 29}, {100, 100, 30}, {101, 101, 31}, {102, 102, 32}, {103, 104, 31}, {105, 105, 33}, {106, 107, 31}, {108, 108, 34}, {109, 109, 31}, {110, 110, 35}, {111, 111, 36}, {112, 114, 31}, {115, 115, 37}, {116, 116, 38}, {117, 117, 39}, {118, 118, 40}, {119, 119, 31}, {120, 120, 41}, {121, 121, 42}, {122, 122, 31}, {123, 123, 43}, },
            {{9, 32, -2}, {92, 92, 25}, },
            {{9, 92, -3}, },
            {{9, 92, -3}, },
            {{9, 92, -3}, },
            {{9, 92, -3}, },
            {},
            {{0, 33, 44}, {34, 34, 45}, {35, 38, 44}, {40, 65535, 44}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{45, 45, 46}, },
            {{46, 46, 47}, {48, 57, 48}, },
            {},
            {{46, 46, 47}, {48, 57, 17}, },
            {},
            {},
            {{60, 60, 49}, {61, 61, 50}, },
            {{61, 61, 51}, },
            {{62, 62, 52}, },
            {{65, 90, 23}, {97, 122, 31}, },
            {},
            {{110, 110, 53}, {114, 114, 54}, {116, 116, 55}, },
            {},
            {{65, 90, 23}, {97, 107, 31}, {108, 108, 56}, {109, 109, 31}, {110, 110, 57}, {111, 114, 31}, {115, 115, 58}, {116, 122, 31}, },
            {{65, 90, 23}, {97, 120, 31}, {121, 121, 59}, {122, 122, 31}, },
            {{65, 90, 23}, {97, 97, 60}, {98, 110, 31}, {111, 111, 61}, {112, 122, 31}, },
            {{65, 90, 23}, {97, 110, 31}, {111, 111, 62}, {112, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 90, 23}, {97, 104, 31}, {105, 105, 63}, {106, 113, 31}, {114, 114, 64}, {115, 122, 31}, },
            {{65, 90, 23}, {97, 109, 31}, {110, 110, 65}, {111, 122, 31}, },
            {{65, 110, -32}, {111, 111, 66}, {112, 122, 31}, },
            {{65, 110, -32}, {111, 111, 67}, {112, 116, 31}, {117, 117, 68}, {118, 122, 31}, },
            {{65, 90, 23}, {97, 113, 31}, {114, 114, 69}, {115, 122, 31}, },
            {{65, 90, 23}, {97, 103, 31}, {104, 104, 70}, {105, 115, 31}, {116, 116, 71}, {117, 120, 31}, {121, 121, 72}, {122, 122, 31}, },
            {{65, 103, -39}, {104, 104, 73}, {105, 110, 31}, {111, 111, 74}, {112, 116, 31}, {117, 117, 75}, {118, 122, 31}, },
            {{65, 109, -35}, {110, 110, 76}, {111, 122, 31}, },
            {{65, 90, 23}, {97, 100, 31}, {101, 101, 77}, {102, 122, 31}, },
            {{65, 110, -32}, {111, 111, 78}, {112, 122, 31}, },
            {{65, 100, -42}, {101, 101, 79}, {102, 122, 31}, },
            {{45, 45, 80}, },
            {{0, 65535, -9}, },
            {},
            {{0, 9, 81}, {11, 12, 81}, {14, 65535, 81}, },
            {{46, 57, -17}, },
            {{48, 57, 48}, },
            {},
            {},
            {},
            {},
            {{9, 92, -3}, },
            {{9, 92, -3}, },
            {{9, 92, -3}, },
            {{65, 90, 23}, {97, 115, 31}, {116, 116, 82}, {117, 122, 31}, },
            {{65, 90, 23}, {97, 99, 31}, {100, 100, 83}, {101, 114, 31}, {115, 115, 84}, {116, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 122, -25}, },
            {{65, 90, 23}, {97, 111, 31}, {112, 112, 85}, {113, 114, 31}, {115, 115, 86}, {116, 122, 31}, },
            {{65, 99, -59}, {100, 100, 87}, {101, 109, 31}, {110, 110, 88}, {111, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 109, -35}, {110, 110, 89}, {111, 122, 31}, },
            {{65, 110, -32}, {111, 111, 90}, {112, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 109, -35}, {110, 110, 91}, {111, 122, 31}, },
            {{65, 115, -58}, {116, 116, 92}, {117, 122, 31}, },
            {{65, 90, 23}, {97, 108, 31}, {109, 109, 93}, {110, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 110, -32}, {111, 111, 94}, {112, 122, 31}, },
            {{65, 90, 23}, {97, 97, 95}, {98, 122, 31}, },
            {{65, 108, -70}, {109, 109, 96}, {110, 122, 31}, },
            {{65, 90, 23}, {97, 97, 97}, {98, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 99, -59}, {100, 100, 98}, {101, 122, 31}, },
            {{65, 90, 23}, {97, 97, 99}, {98, 122, 31}, },
            {{65, 90, 23}, {97, 98, 31}, {99, 99, 100}, {100, 122, 31}, },
            {{65, 113, -38}, {114, 114, 101}, {115, 122, 31}, },
            {{65, 90, 23}, {97, 114, 31}, {115, 115, 102}, {116, 122, 31}, },
            {{0, 44, 103}, {45, 45, 104}, {46, 122, 103}, {124, 65535, 103}, },
            {{0, 65535, -48}, },
            {{65, 100, -42}, {101, 101, 105}, {102, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 90, 23}, {97, 118, 31}, {119, 119, 106}, {120, 122, 31}, },
            {{65, 115, -58}, {116, 116, 107}, {117, 122, 31}, },
            {{65, 100, -42}, {101, 101, 108}, {102, 122, 31}, },
            {{65, 100, -42}, {101, 101, 109}, {102, 122, 31}, },
            {{65, 114, -81}, {115, 115, 110}, {116, 122, 31}, },
            {{65, 104, -34}, {105, 105, 111}, {106, 122, 31}, },
            {{65, 108, -70}, {109, 109, 112}, {110, 122, 31}, },
            {{65, 90, 23}, {97, 102, 31}, {103, 103, 113}, {104, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 90, 23}, {97, 97, 31}, {98, 98, 114}, {99, 122, 31}, },
            {{65, 118, -86}, {119, 119, 115}, {120, 122, 31}, },
            {{65, 113, -38}, {114, 114, 116}, {115, 122, 31}, },
            {{65, 97, -95}, {98, 98, 117}, {99, 122, 31}, },
            {{65, 115, -58}, {116, 116, 118}, {117, 122, 31}, },
            {{65, 110, -32}, {111, 111, 119}, {112, 122, 31}, },
            {{65, 107, -29}, {108, 108, 120}, {109, 122, 31}, },
            {{65, 115, -58}, {116, 116, 121}, {117, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 122, -25}, },
            {{0, 65535, -82}, },
            {{0, 122, -82}, {124, 124, 103}, {125, 125, 122}, {126, 65535, 103}, },
            {{65, 113, -38}, {114, 114, 123}, {115, 122, 31}, },
            {{65, 100, -42}, {101, 101, 124}, {102, 122, 31}, },
            {{65, 90, 23}, {97, 116, 31}, {117, 117, 125}, {118, 122, 31}, },
            {{65, 122, -25}, },
            {{0, 9, 126}, {11, 12, 126}, {14, 64, 126}, {65, 90, 127}, {91, 96, 126}, {97, 122, 128}, {123, 65535, 126}, },
            {{65, 104, -34}, {105, 105, 129}, {106, 122, 31}, },
            {{65, 114, -81}, {115, 115, 130}, {116, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 122, -25}, },
            {{65, 100, -42}, {101, 101, 131}, {102, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 115, -58}, {116, 116, 132}, {117, 122, 31}, },
            {{65, 110, -32}, {111, 111, 133}, {112, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 90, 23}, {95, 95, 134}, {97, 122, 31}, },
            {{65, 115, -58}, {116, 116, 135}, {117, 122, 31}, },
            {{65, 110, -32}, {111, 111, 136}, {112, 122, 31}, },
            {{0, 65535, -82}, },
            {{65, 90, 23}, {97, 97, 137}, {98, 122, 31}, },
            {{65, 113, -38}, {114, 114, 138}, {115, 122, 31}, },
            {{65, 113, -38}, {114, 114, 139}, {115, 122, 31}, },
            {{0, 12, -111}, {14, 65535, 126}, },
            {{0, 65535, -111}, },
            {{0, 65535, -111}, },
            {{65, 99, -59}, {100, 100, 140}, {101, 122, 31}, },
            {{65, 103, -39}, {104, 104, 141}, {105, 122, 31}, },
            {{65, 113, -38}, {114, 114, 142}, {115, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 107, -29}, {108, 108, 143}, {109, 122, 31}, },
            {{117, 117, 144}, },
            {{65, 100, -42}, {101, 101, 145}, {102, 122, 31}, },
            {{65, 113, -38}, {114, 114, 146}, {115, 122, 31}, },
            {{65, 97, -95}, {98, 98, 147}, {99, 122, 31}, },
            {{65, 90, 23}, {91, 91, 148}, {97, 122, 31}, },
            {{65, 100, -42}, {101, 101, 149}, {102, 122, 31}, },
            {{65, 100, -42}, {101, 101, 150}, {102, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 122, -140}, },
            {{65, 122, -140}, },
            {{110, 110, 151}, },
            {{65, 113, -38}, {114, 114, 152}, {115, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 107, -29}, {108, 108, 153}, {109, 122, 31}, },
            {{48, 57, 154}, },
            {{65, 122, -25}, },
            {{65, 113, -38}, {114, 114, 155}, {115, 122, 31}, },
            {{105, 105, 156}, },
            {{65, 90, 23}, {97, 97, 157}, {98, 122, 31}, },
            {{65, 100, -42}, {101, 101, 158}, {102, 122, 31}, },
            {{93, 93, 159}, },
            {{65, 104, -34}, {105, 105, 160}, {106, 122, 31}, },
            {{99, 99, 161}, },
            {{65, 97, -95}, {98, 98, 162}, {99, 122, 31}, },
            {{65, 122, -25}, },
            {{65, 90, 163}, {91, 91, 148}, {97, 122, 164}, },
            {{65, 109, -35}, {110, 110, 165}, {111, 122, 31}, },
            {{111, 111, 166}, },
            {{65, 107, -29}, {108, 108, 167}, {109, 122, 31}, },
            {{65, 90, 163}, {97, 122, 164}, },
            {{65, 122, -165}, },
            {{65, 102, -93}, {103, 103, 168}, {104, 122, 31}, },
            {{100, 100, 169}, },
            {{65, 100, -42}, {101, 101, 170}, {102, 122, 31}, },
            {{65, 122, -25}, },
            {{101, 101, 171}, },
            {{65, 122, -25}, },
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {11, 50, 50, 50, 50, 50, 21, 8, 16, 2, 3, 14, 12, 5, 13, 7, 15, 11, 4, 6, 18, -1, -1, 42, 9, -1, 10, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, -1, -1, 48, 40, 11, 11, 17, 19, 20, 22, 50, 50, 50, 42, 42, 30, 29, 42, 42, 36, 42, 42, 23, 42, 42, 42, 33, 42, 42, 42, 42, 28, 42, 42, 42, 42, 42, -1, 40, 42, 32, 42, 42, 42, 42, 42, 42, 42, 42, 34, 42, 42, 42, 42, 42, 42, 42, 42, 35, 42, -1, -1, 42, 42, 42, 24, 37, 42, 42, 27, 31, 42, 38, 42, 42, 25, 42, 42, 42, 41, 42, 42, 42, 37, 37, 37, 42, 42, 42, 0, 42, -1, 42, 42, 42, 42, 42, 42, 1, 42, 42, -1, 42, 42, 42, -1, 39, 42, -1, 42, 42, -1, 42, -1, 42, 42, 49, 42, -1, 42, 49, 49, 42, -1, 42, 26, -1, 42, 44, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
