/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.lexer;

import java.io.*;
import cida.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbreBloco(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechaBloco(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParEsq(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParDir(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoisPontos(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoVirgula(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAspas(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColcheteEsq(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColcheteDir(line, pos); }
    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumeros(text, line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSoma(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenos(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribuicao(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenor(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaior(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorIgual(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorIgual(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComparacao(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiferente(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIn(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCase(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOtherwise(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThat(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConsidering(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFrom(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTo(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBy(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAs(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLong(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnd(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOr(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNot(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TXor(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDo(line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCode(text, line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TShow(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCapture(line, pos); }
    Token new42(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioLinha(text, line, pos); }
    Token new43(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioBloco(text, line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUnalterable(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAlterable(line, pos); }
    Token new46(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSymbol(text, line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnswer(line, pos); }
    Token new49(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBooleano(text, line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVector(line, pos); }
    Token new51(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVetorSymbol(text, line, pos); }
    Token new52(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVetores(text, line, pos); }
    Token new53(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new54(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVazio(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {12, 12, 3}, {13, 13, 4}, {32, 32, 5}, {33, 33, 6}, {34, 34, 7}, {37, 37, 8}, {39, 39, 9}, {40, 40, 10}, {41, 41, 11}, {42, 42, 12}, {43, 43, 13}, {44, 44, 14}, {45, 45, 15}, {46, 46, 16}, {47, 47, 17}, {48, 57, 18}, {58, 58, 19}, {59, 59, 20}, {60, 60, 21}, {61, 61, 22}, {62, 62, 23}, {65, 90, 24}, {91, 91, 25}, {92, 92, 26}, {93, 93, 27}, {97, 97, 28}, {98, 98, 29}, {99, 99, 30}, {100, 100, 31}, {101, 101, 32}, {102, 102, 33}, {103, 104, 32}, {105, 105, 34}, {106, 107, 32}, {108, 108, 35}, {109, 109, 32}, {110, 110, 36}, {111, 111, 37}, {112, 114, 32}, {115, 115, 38}, {116, 116, 39}, {117, 117, 40}, {118, 118, 41}, {119, 119, 32}, {120, 120, 42}, {121, 121, 43}, {122, 122, 32}, {123, 123, 44}, },
            {{9, 32, -2}, {92, 92, 26}, },
            {{9, 92, -3}, },
            {{9, 92, -3}, },
            {{9, 92, -3}, },
            {{9, 92, -3}, },
            {{61, 61, 45}, },
            {{0, 33, 46}, {34, 34, 47}, {35, 38, 46}, {40, 65535, 46}, },
            {},
            {{0, 33, 48}, {35, 38, 48}, {40, 65535, 48}, },
            {},
            {},
            {},
            {},
            {},
            {{45, 45, 49}, },
            {{48, 57, 50}, },
            {},
            {{46, 46, 51}, {48, 57, 18}, },
            {},
            {},
            {{60, 60, 52}, {61, 61, 53}, },
            {{61, 61, 54}, },
            {{61, 61, 55}, },
            {{65, 90, 24}, {97, 122, 32}, },
            {},
            {{110, 110, 56}, {114, 114, 57}, {116, 116, 58}, },
            {},
            {{65, 90, 24}, {97, 107, 32}, {108, 108, 59}, {109, 109, 32}, {110, 110, 60}, {111, 114, 32}, {115, 115, 61}, {116, 122, 32}, },
            {{65, 90, 24}, {97, 120, 32}, {121, 121, 62}, {122, 122, 32}, },
            {{65, 90, 24}, {97, 97, 63}, {98, 110, 32}, {111, 111, 64}, {112, 122, 32}, },
            {{65, 90, 24}, {97, 110, 32}, {111, 111, 65}, {112, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 90, 24}, {97, 104, 32}, {105, 105, 66}, {106, 113, 32}, {114, 114, 67}, {115, 122, 32}, },
            {{65, 90, 24}, {97, 109, 32}, {110, 110, 68}, {111, 122, 32}, },
            {{65, 110, -33}, {111, 111, 69}, {112, 122, 32}, },
            {{65, 110, -33}, {111, 111, 70}, {112, 116, 32}, {117, 117, 71}, {118, 122, 32}, },
            {{65, 90, 24}, {97, 113, 32}, {114, 114, 72}, {115, 115, 32}, {116, 116, 73}, {117, 122, 32}, },
            {{65, 90, 24}, {97, 103, 32}, {104, 104, 74}, {105, 115, 32}, {116, 116, 75}, {117, 120, 32}, {121, 121, 76}, {122, 122, 32}, },
            {{65, 103, -40}, {104, 104, 77}, {105, 110, 32}, {111, 111, 78}, {112, 122, 32}, },
            {{65, 109, -36}, {110, 110, 79}, {111, 122, 32}, },
            {{65, 90, 24}, {97, 100, 32}, {101, 101, 80}, {102, 122, 32}, },
            {{65, 110, -33}, {111, 111, 81}, {112, 122, 32}, },
            {{65, 100, -43}, {101, 101, 82}, {102, 122, 32}, },
            {{45, 45, 83}, },
            {},
            {{0, 65535, -9}, },
            {},
            {{39, 39, 84}, },
            {{0, 9, 85}, {11, 12, 85}, {14, 65535, 85}, },
            {{48, 57, 50}, },
            {{48, 57, 50}, },
            {},
            {},
            {},
            {},
            {{9, 92, -3}, },
            {{9, 92, -3}, },
            {{9, 92, -3}, },
            {{65, 90, 24}, {97, 115, 32}, {116, 116, 86}, {117, 122, 32}, },
            {{65, 90, 24}, {97, 99, 32}, {100, 100, 87}, {101, 114, 32}, {115, 115, 88}, {116, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 90, 24}, {97, 111, 32}, {112, 112, 89}, {113, 114, 32}, {115, 115, 90}, {116, 122, 32}, },
            {{65, 99, -62}, {100, 100, 91}, {101, 109, 32}, {110, 110, 92}, {111, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 109, -36}, {110, 110, 93}, {111, 122, 32}, },
            {{65, 110, -33}, {111, 111, 94}, {112, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 109, -36}, {110, 110, 95}, {111, 122, 32}, },
            {{65, 115, -61}, {116, 116, 96}, {117, 122, 32}, },
            {{65, 90, 24}, {97, 108, 32}, {109, 109, 97}, {110, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 103, -40}, {104, 104, 98}, {105, 122, 32}, },
            {{65, 110, -33}, {111, 111, 99}, {112, 122, 32}, },
            {{65, 90, 24}, {97, 97, 100}, {98, 122, 32}, },
            {{65, 108, -73}, {109, 109, 101}, {110, 122, 32}, },
            {{65, 90, 24}, {97, 97, 102}, {98, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 90, 24}, {97, 97, 103}, {98, 122, 32}, },
            {{65, 90, 24}, {97, 98, 32}, {99, 99, 104}, {100, 122, 32}, },
            {{65, 113, -39}, {114, 114, 105}, {115, 122, 32}, },
            {{65, 90, 24}, {97, 114, 32}, {115, 115, 106}, {116, 122, 32}, },
            {{0, 44, 107}, {45, 45, 108}, {46, 122, 107}, {124, 65535, 107}, },
            {},
            {{0, 65535, -51}, },
            {{65, 100, -43}, {101, 101, 109}, {102, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 90, 24}, {97, 118, 32}, {119, 119, 110}, {120, 122, 32}, },
            {{65, 115, -61}, {116, 116, 111}, {117, 122, 32}, },
            {{65, 100, -43}, {101, 101, 112}, {102, 122, 32}, },
            {{65, 100, -43}, {101, 101, 113}, {102, 122, 32}, },
            {{65, 114, -84}, {115, 115, 114}, {116, 122, 32}, },
            {{65, 104, -35}, {105, 105, 115}, {106, 122, 32}, },
            {{65, 108, -73}, {109, 109, 116}, {110, 122, 32}, },
            {{65, 90, 24}, {97, 102, 32}, {103, 103, 117}, {104, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 90, 24}, {97, 97, 32}, {98, 98, 118}, {99, 122, 32}, },
            {{65, 100, -43}, {101, 101, 119}, {102, 122, 32}, },
            {{65, 118, -90}, {119, 119, 120}, {120, 122, 32}, },
            {{65, 113, -39}, {114, 114, 121}, {115, 122, 32}, },
            {{65, 97, -99}, {98, 98, 122}, {99, 122, 32}, },
            {{65, 115, -61}, {116, 116, 123}, {117, 122, 32}, },
            {{65, 107, -30}, {108, 108, 124}, {109, 122, 32}, },
            {{65, 115, -61}, {116, 116, 125}, {117, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{0, 65535, -85}, },
            {{0, 122, -85}, {124, 124, 107}, {125, 125, 126}, {126, 65535, 107}, },
            {{65, 113, -39}, {114, 114, 127}, {115, 122, 32}, },
            {{65, 100, -43}, {101, 101, 128}, {102, 122, 32}, },
            {{65, 90, 24}, {97, 116, 32}, {117, 117, 129}, {118, 122, 32}, },
            {{65, 122, -26}, },
            {{0, 33, 130}, {35, 38, 130}, {40, 64, 130}, {65, 90, 131}, {91, 96, 130}, {97, 122, 132}, {123, 65535, 130}, },
            {{65, 104, -35}, {105, 105, 133}, {106, 122, 32}, },
            {{65, 114, -84}, {115, 115, 134}, {116, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 100, -43}, {101, 101, 135}, {102, 122, 32}, },
            {{65, 113, -39}, {114, 114, 136}, {115, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 115, -61}, {116, 116, 137}, {117, 122, 32}, },
            {{65, 110, -33}, {111, 111, 138}, {112, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 115, -61}, {116, 116, 139}, {117, 122, 32}, },
            {{65, 110, -33}, {111, 111, 140}, {112, 122, 32}, },
            {{0, 65535, -85}, },
            {{65, 90, 24}, {97, 97, 141}, {98, 122, 32}, },
            {{65, 113, -39}, {114, 114, 142}, {115, 122, 32}, },
            {{65, 113, -39}, {114, 114, 143}, {115, 122, 32}, },
            {},
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 99, -62}, {100, 100, 144}, {101, 122, 32}, },
            {{65, 103, -40}, {104, 104, 145}, {105, 122, 32}, },
            {{65, 113, -39}, {114, 114, 146}, {115, 122, 32}, },
            {{65, 118, -90}, {119, 119, 147}, {120, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 107, -30}, {108, 108, 148}, {109, 122, 32}, },
            {{65, 100, -43}, {101, 101, 149}, {102, 122, 32}, },
            {{65, 113, -39}, {114, 114, 150}, {115, 122, 32}, },
            {{65, 97, -99}, {98, 98, 151}, {99, 122, 32}, },
            {{65, 90, 24}, {91, 91, 152}, {97, 122, 32}, },
            {{65, 100, -43}, {101, 101, 153}, {102, 122, 32}, },
            {{65, 100, -43}, {101, 101, 154}, {102, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 122, -144}, },
            {{65, 104, -35}, {105, 105, 155}, {106, 122, 32}, },
            {{65, 122, -144}, },
            {{65, 113, -39}, {114, 114, 156}, {115, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 107, -30}, {108, 108, 157}, {109, 122, 32}, },
            {{48, 57, 158}, },
            {{65, 122, -26}, },
            {{65, 113, -39}, {114, 114, 159}, {115, 122, 32}, },
            {{65, 114, -84}, {115, 115, 160}, {116, 122, 32}, },
            {{65, 90, 24}, {97, 97, 161}, {98, 122, 32}, },
            {{65, 100, -43}, {101, 101, 162}, {102, 122, 32}, },
            {{93, 93, 163}, },
            {{65, 104, -35}, {105, 105, 164}, {106, 122, 32}, },
            {{65, 100, -43}, {101, 101, 165}, {102, 122, 32}, },
            {{65, 97, -99}, {98, 98, 166}, {99, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 90, 167}, {91, 91, 152}, {97, 122, 168}, },
            {{65, 109, -36}, {110, 110, 169}, {111, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 107, -30}, {108, 108, 170}, {109, 122, 32}, },
            {{65, 90, 167}, {97, 122, 168}, },
            {{65, 122, -169}, },
            {{65, 102, -97}, {103, 103, 171}, {104, 122, 32}, },
            {{65, 100, -43}, {101, 101, 172}, {102, 122, 32}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {11, 54, 54, 54, 54, 54, -1, 8, 16, -1, 2, 3, 14, 12, 5, 13, 7, 15, 11, 4, 6, 18, -1, 19, 53, 9, -1, 10, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, -1, 23, -1, 51, -1, 42, 11, -1, 17, 21, 22, 20, 54, 54, 54, 53, 53, 32, 31, 53, 53, 38, 53, 53, 24, 53, 49, 53, 35, 53, 53, 53, 53, 53, 30, 53, 53, 53, 53, -1, 46, 42, 53, 34, 53, 53, 53, 53, 53, 53, 53, 53, 36, 53, 53, 53, 53, 53, 53, 53, 53, 37, 49, -1, -1, 53, 53, 53, 25, 53, 53, 53, 29, 33, 53, 53, 40, 53, 53, 27, 53, 53, 43, 53, 53, 53, 39, 39, 39, 53, 53, 53, 53, 0, 53, 53, 53, 53, 48, 53, 53, 1, 47, 53, 53, 53, 50, 53, -1, 41, 53, 53, 53, 53, -1, 53, 53, 53, 45, 52, 53, 26, 53, 52, 52, 53, 53, 28, 44, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
