/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AAProgramaAPrograma extends PAPrograma
{
    private TId _id_;
    private PABloco _aBloco_;

    public AAProgramaAPrograma()
    {
        // Constructor
    }

    public AAProgramaAPrograma(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PABloco _aBloco_)
    {
        // Constructor
        setId(_id_);

        setABloco(_aBloco_);

    }

    @Override
    public Object clone()
    {
        return new AAProgramaAPrograma(
            cloneNode(this._id_),
            cloneNode(this._aBloco_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAProgramaAPrograma(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PABloco getABloco()
    {
        return this._aBloco_;
    }

    public void setABloco(PABloco node)
    {
        if(this._aBloco_ != null)
        {
            this._aBloco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aBloco_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._aBloco_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._aBloco_ == child)
        {
            this._aBloco_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._aBloco_ == oldChild)
        {
            setABloco((PABloco) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
