/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AConsideringAComandoComposto extends PAComandoComposto
{
    private PALocal _aLocal_;
    private PExpr _exp1_;
    private PExpr _exp2_;
    private PExpr _exp3_;
    private PAComandoComposto _aComandoComposto_;

    public AConsideringAComandoComposto()
    {
        // Constructor
    }

    public AConsideringAComandoComposto(
        @SuppressWarnings("hiding") PALocal _aLocal_,
        @SuppressWarnings("hiding") PExpr _exp1_,
        @SuppressWarnings("hiding") PExpr _exp2_,
        @SuppressWarnings("hiding") PExpr _exp3_,
        @SuppressWarnings("hiding") PAComandoComposto _aComandoComposto_)
    {
        // Constructor
        setALocal(_aLocal_);

        setExp1(_exp1_);

        setExp2(_exp2_);

        setExp3(_exp3_);

        setAComandoComposto(_aComandoComposto_);

    }

    @Override
    public Object clone()
    {
        return new AConsideringAComandoComposto(
            cloneNode(this._aLocal_),
            cloneNode(this._exp1_),
            cloneNode(this._exp2_),
            cloneNode(this._exp3_),
            cloneNode(this._aComandoComposto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConsideringAComandoComposto(this);
    }

    public PALocal getALocal()
    {
        return this._aLocal_;
    }

    public void setALocal(PALocal node)
    {
        if(this._aLocal_ != null)
        {
            this._aLocal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aLocal_ = node;
    }

    public PExpr getExp1()
    {
        return this._exp1_;
    }

    public void setExp1(PExpr node)
    {
        if(this._exp1_ != null)
        {
            this._exp1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp1_ = node;
    }

    public PExpr getExp2()
    {
        return this._exp2_;
    }

    public void setExp2(PExpr node)
    {
        if(this._exp2_ != null)
        {
            this._exp2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp2_ = node;
    }

    public PExpr getExp3()
    {
        return this._exp3_;
    }

    public void setExp3(PExpr node)
    {
        if(this._exp3_ != null)
        {
            this._exp3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp3_ = node;
    }

    public PAComandoComposto getAComandoComposto()
    {
        return this._aComandoComposto_;
    }

    public void setAComandoComposto(PAComandoComposto node)
    {
        if(this._aComandoComposto_ != null)
        {
            this._aComandoComposto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aComandoComposto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aLocal_)
            + toString(this._exp1_)
            + toString(this._exp2_)
            + toString(this._exp3_)
            + toString(this._aComandoComposto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aLocal_ == child)
        {
            this._aLocal_ = null;
            return;
        }

        if(this._exp1_ == child)
        {
            this._exp1_ = null;
            return;
        }

        if(this._exp2_ == child)
        {
            this._exp2_ = null;
            return;
        }

        if(this._exp3_ == child)
        {
            this._exp3_ = null;
            return;
        }

        if(this._aComandoComposto_ == child)
        {
            this._aComandoComposto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aLocal_ == oldChild)
        {
            setALocal((PALocal) newChild);
            return;
        }

        if(this._exp1_ == oldChild)
        {
            setExp1((PExpr) newChild);
            return;
        }

        if(this._exp2_ == oldChild)
        {
            setExp2((PExpr) newChild);
            return;
        }

        if(this._exp3_ == oldChild)
        {
            setExp3((PExpr) newChild);
            return;
        }

        if(this._aComandoComposto_ == oldChild)
        {
            setAComandoComposto((PAComandoComposto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
