/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class ADecUnalterableADeclaracao extends PADeclaracao
{
    private PATipoBase _aTipoBase_;
    private TId _id_;
    private PExpr _expr_;

    public ADecUnalterableADeclaracao()
    {
        // Constructor
    }

    public ADecUnalterableADeclaracao(
        @SuppressWarnings("hiding") PATipoBase _aTipoBase_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setATipoBase(_aTipoBase_);

        setId(_id_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new ADecUnalterableADeclaracao(
            cloneNode(this._aTipoBase_),
            cloneNode(this._id_),
            cloneNode(this._expr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecUnalterableADeclaracao(this);
    }

    public PATipoBase getATipoBase()
    {
        return this._aTipoBase_;
    }

    public void setATipoBase(PATipoBase node)
    {
        if(this._aTipoBase_ != null)
        {
            this._aTipoBase_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aTipoBase_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aTipoBase_)
            + toString(this._id_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aTipoBase_ == child)
        {
            this._aTipoBase_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aTipoBase_ == oldChild)
        {
            setATipoBase((PATipoBase) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
