/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AExpLocalExpTerminal extends PExpTerminal
{
    private PLocal _local_;

    public AExpLocalExpTerminal()
    {
        // Constructor
    }

    public AExpLocalExpTerminal(
        @SuppressWarnings("hiding") PLocal _local_)
    {
        // Constructor
        setLocal(_local_);

    }

    @Override
    public Object clone()
    {
        return new AExpLocalExpTerminal(
            cloneNode(this._local_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpLocalExpTerminal(this);
    }

    public PLocal getLocal()
    {
        return this._local_;
    }

    public void setLocal(PLocal node)
    {
        if(this._local_ != null)
        {
            this._local_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._local_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._local_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._local_ == child)
        {
            this._local_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._local_ == oldChild)
        {
            setLocal((PLocal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
