/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AExpSomaExp extends PExp
{
    private PExp _exp_;
    private TSoma _soma_;
    private PExpTerminal _expTerminal_;

    public AExpSomaExp()
    {
        // Constructor
    }

    public AExpSomaExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TSoma _soma_,
        @SuppressWarnings("hiding") PExpTerminal _expTerminal_)
    {
        // Constructor
        setExp(_exp_);

        setSoma(_soma_);

        setExpTerminal(_expTerminal_);

    }

    @Override
    public Object clone()
    {
        return new AExpSomaExp(
            cloneNode(this._exp_),
            cloneNode(this._soma_),
            cloneNode(this._expTerminal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpSomaExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TSoma getSoma()
    {
        return this._soma_;
    }

    public void setSoma(TSoma node)
    {
        if(this._soma_ != null)
        {
            this._soma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._soma_ = node;
    }

    public PExpTerminal getExpTerminal()
    {
        return this._expTerminal_;
    }

    public void setExpTerminal(PExpTerminal node)
    {
        if(this._expTerminal_ != null)
        {
            this._expTerminal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expTerminal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._soma_)
            + toString(this._expTerminal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._soma_ == child)
        {
            this._soma_ = null;
            return;
        }

        if(this._expTerminal_ == child)
        {
            this._expTerminal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._soma_ == oldChild)
        {
            setSoma((TSoma) newChild);
            return;
        }

        if(this._expTerminal_ == oldChild)
        {
            setExpTerminal((PExpTerminal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
