/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AExpTerminalExp extends PExp
{
    private PExpTerminal _expTerminal_;

    public AExpTerminalExp()
    {
        // Constructor
    }

    public AExpTerminalExp(
        @SuppressWarnings("hiding") PExpTerminal _expTerminal_)
    {
        // Constructor
        setExpTerminal(_expTerminal_);

    }

    @Override
    public Object clone()
    {
        return new AExpTerminalExp(
            cloneNode(this._expTerminal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpTerminalExp(this);
    }

    public PExpTerminal getExpTerminal()
    {
        return this._expTerminal_;
    }

    public void setExpTerminal(PExpTerminal node)
    {
        if(this._expTerminal_ != null)
        {
            this._expTerminal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expTerminal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expTerminal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expTerminal_ == child)
        {
            this._expTerminal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expTerminal_ == oldChild)
        {
            setExpTerminal((PExpTerminal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
