/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class ALocalVirgulaALocalVirgula extends PALocalVirgula
{
    private PALocal _aLocal_;
    private TVirgula _virgula_;

    public ALocalVirgulaALocalVirgula()
    {
        // Constructor
    }

    public ALocalVirgulaALocalVirgula(
        @SuppressWarnings("hiding") PALocal _aLocal_,
        @SuppressWarnings("hiding") TVirgula _virgula_)
    {
        // Constructor
        setALocal(_aLocal_);

        setVirgula(_virgula_);

    }

    @Override
    public Object clone()
    {
        return new ALocalVirgulaALocalVirgula(
            cloneNode(this._aLocal_),
            cloneNode(this._virgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALocalVirgulaALocalVirgula(this);
    }

    public PALocal getALocal()
    {
        return this._aLocal_;
    }

    public void setALocal(PALocal node)
    {
        if(this._aLocal_ != null)
        {
            this._aLocal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aLocal_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aLocal_)
            + toString(this._virgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aLocal_ == child)
        {
            this._aLocal_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aLocal_ == oldChild)
        {
            setALocal((PALocal) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
