/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class ALocalVirgulaLocalVirgula extends PLocalVirgula
{
    private PLocal _local_;
    private TVirgula _virgula_;

    public ALocalVirgulaLocalVirgula()
    {
        // Constructor
    }

    public ALocalVirgulaLocalVirgula(
        @SuppressWarnings("hiding") PLocal _local_,
        @SuppressWarnings("hiding") TVirgula _virgula_)
    {
        // Constructor
        setLocal(_local_);

        setVirgula(_virgula_);

    }

    @Override
    public Object clone()
    {
        return new ALocalVirgulaLocalVirgula(
            cloneNode(this._local_),
            cloneNode(this._virgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALocalVirgulaLocalVirgula(this);
    }

    public PLocal getLocal()
    {
        return this._local_;
    }

    public void setLocal(PLocal node)
    {
        if(this._local_ != null)
        {
            this._local_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._local_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._local_)
            + toString(this._virgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._local_ == child)
        {
            this._local_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._local_ == oldChild)
        {
            setLocal((PLocal) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
