/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class AMenosExp7 extends PExp7
{
    private TMenos _menos_;
    private PExp7 _exp7_;

    public AMenosExp7()
    {
        // Constructor
    }

    public AMenosExp7(
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PExp7 _exp7_)
    {
        // Constructor
        setMenos(_menos_);

        setExp7(_exp7_);

    }

    @Override
    public Object clone()
    {
        return new AMenosExp7(
            cloneNode(this._menos_),
            cloneNode(this._exp7_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenosExp7(this);
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PExp7 getExp7()
    {
        return this._exp7_;
    }

    public void setExp7(PExp7 node)
    {
        if(this._exp7_ != null)
        {
            this._exp7_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp7_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menos_)
            + toString(this._exp7_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._exp7_ == child)
        {
            this._exp7_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._exp7_ == oldChild)
        {
            setExp7((PExp7) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
