/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import java.util.*;
import cida.analysis.*;

@SuppressWarnings("nls")
public final class ATipoVectorATipo extends PATipo
{
    private PATipoBase _aTipoBase_;
    private PExpr _expr_;
    private final LinkedList<PAColcheteVector> _aColcheteVector_ = new LinkedList<PAColcheteVector>();

    public ATipoVectorATipo()
    {
        // Constructor
    }

    public ATipoVectorATipo(
        @SuppressWarnings("hiding") PATipoBase _aTipoBase_,
        @SuppressWarnings("hiding") PExpr _expr_,
        @SuppressWarnings("hiding") List<?> _aColcheteVector_)
    {
        // Constructor
        setATipoBase(_aTipoBase_);

        setExpr(_expr_);

        setAColcheteVector(_aColcheteVector_);

    }

    @Override
    public Object clone()
    {
        return new ATipoVectorATipo(
            cloneNode(this._aTipoBase_),
            cloneNode(this._expr_),
            cloneList(this._aColcheteVector_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATipoVectorATipo(this);
    }

    public PATipoBase getATipoBase()
    {
        return this._aTipoBase_;
    }

    public void setATipoBase(PATipoBase node)
    {
        if(this._aTipoBase_ != null)
        {
            this._aTipoBase_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aTipoBase_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    public LinkedList<PAColcheteVector> getAColcheteVector()
    {
        return this._aColcheteVector_;
    }

    public void setAColcheteVector(List<?> list)
    {
        for(PAColcheteVector e : this._aColcheteVector_)
        {
            e.parent(null);
        }
        this._aColcheteVector_.clear();

        for(Object obj_e : list)
        {
            PAColcheteVector e = (PAColcheteVector) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aColcheteVector_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aTipoBase_)
            + toString(this._expr_)
            + toString(this._aColcheteVector_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aTipoBase_ == child)
        {
            this._aTipoBase_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        if(this._aColcheteVector_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aTipoBase_ == oldChild)
        {
            setATipoBase((PATipoBase) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        for(ListIterator<PAColcheteVector> i = this._aColcheteVector_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAColcheteVector) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
